HealerOne/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('serena.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

serena/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index')
]

serena/models.py
from django.db import models

# Create your models here.

# HOME SECTION


class Home(models.Model):
    name = models.CharField(max_length=30)
    greetings_1 = models.CharField(max_length=10)
    greetings_2 = models.CharField(max_length=10)
    picture = models.ImageField(upload_to='picture/')
    # save time when modified
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

# ABOUT SECTION


class About(models.Model):
    heading = models.CharField(max_length=50)
    career = models.CharField(max_length=20)
    description = models.TextField(blank=False)
    profile_img = models.ImageField(upload_to='profile/')
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.career


class Profile(models.Model):
    about = models.ForeignKey(About, on_delete=models.CASCADE)
    social_name = models.CharField(max_length=10)
    link = models.URLField(max_length=200)

# SKILLS SECTION


class Category(models.Model):
    name = models.CharField(max_length=20)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Skill'
        verbose_name_plural = 'Skills'

    def __str__(self):
        return self.name


class Skills(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    skill_name = models.CharField(max_length=20)

# PORTFOLIO SECTION


class Portfolio(models.Model):
    image = models.ImageField(upload_to='portfolio/')
    short_description = models.CharField(max_length=20)
    long_description = models.CharField(max_length=200)

    def __str__(self):
        return f'Portfolio {self.id}'

serena/views.py
from django.shortcuts import render
from .models import Home, About, Profile, Category, Skills, Portfolio

# Create your views here.


def index(request):

    # HOME
    home = Home.objects.latest('updated')

    # ABOUT
    about = About.objects.latest('updated')
    profiles = Profile.objects.filter(about=about)

    # SKILLS
    categories = Category.objects.all()

    # PORTFOLIO
    portfolios = Portfolio.objects.all()

    context = {
        'home': home,
        'about': about,
        'profiles': profiles,
        'categories': categories,
        'portfolios': portfolios,

    }

    return render(request, 'index.html', context)

serena/templates/index.html
{% load static %}

<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- ===== CSS ===== -->
        <link id="stylesheet1" rel="stylesheet" href="{% static 'assets/css/styles.css' %}">

        <!-- ===== GALLERY CSS ===== -->
        <link rel="stylesheet" href="{% static 'assets/css/lightbox.min.css' %}">

        <!-- ===== BOX ICONS ===== -->
        <link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>

        <link rel="icon" href="{% static 'assets/img/favicon.ico' %}">

        <!-- ===== FONT AWESOME ==== -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
    </head>
    <body>
        <!--===== HEADER =====-->
        <header class="l-header">
            <nav class="nav bd-grid">
                <div>
                    <a href="#" class="nav__logo">{{ home.name }}</a>
                </div>

                <div class="nav__menu" id="nav-menu">
                    <ul class="nav__list">
                        <li class="nav__item"><a href="#home" class="nav__link active">Home</a></li>
                        <li class="nav__item"><a href="#about" class="nav__link">About</a></li>
                        <li class="nav__item"><a href="#skills" class="nav__link">Games</a></li>
                        <li class="nav__item"><a href="#portfolio" class="nav__link">Gallery</a></li>
                        <li class="nav__item"><i onclick="swapStyle('{% static 'assets/css/styles.css' %}')" class="fas fa-sun"></i></li>
                        <li class="nav__item"><i onclick="swapStyle('{% static 'assets/css/dark.css' %}')" class="fas fa-moon"></i></li>
                    </ul>
                </div>
                <div class="nav__toggle" id="nav-toggle">
                    <i class='bx bx-menu'></i>
                </div>
            </nav>
        </header>

        <main class="l-main">
            <!--===== HOME =====-->
            <section class="home" id="home">
                <div class="home__container bd-grid">
                    <h1 class="home__title"><span>{{ home.greetings_1 }}</span><br>{{ home.greetings_2 }}</h1>

                    <div class="home__scroll">
                        <a href="#about" class="home__scroll-link"><i class='bx bx-up-arrow-alt' ></i>Scroll down</a>
                    </div>

                    <img src="{{ home.picture.url }}" alt="" class="home__img">
                </div>
            </section>
            
            <!--===== ABOUT =====-->
            <section class="about section" id="about">
                <h2 class="section-title">About</h2>

                <div class="about__container bd-grid">
                    <div class="about_img">
                        <img src="{{ about.profile_img.url }}" alt="">
                    </div>

                    <div>
                        <h2 class="about__subtitle">{{ about.heading }}</h2>
                        <span class="about__profession">{{ about.career }}</span>
                        <p class="about__text">{{ about.description }}</p>

                        <div class="about__social">
                            <a href="https://thehealerone.tumblr.com/" class="about__social-icon"><i class='bx bxl-tumblr' ></i></a>
                        </div>

                    </div>
                </div>
            </section>

            <!--===== GAMES - SKILLS =====-->
            <section class="skills section" id="skills">
                <h2 class="section-title">Games</h2>

                <div class="skills__container bd-grid">
                    <div class="skills__box">
                        <div class="skills__box">
                        {% for category in categories %}
                        <h3 class="skills__subtitle">{{ category.name }}</h3>
                            {% for skills in category.skills_set.all %}
                                <span class="skills__name">{{ skills.skill_name }}</span>
                            {% endfor %}
                        {% endfor %}
                        </div>
                    </div>

                    <div class="skills__img">
                        <img src="{% static 'assets/img/games.jpg' %}" alt="">
                    </div>
                </div>
            </section>

            <!--===== GALLERY - PORTFOLIO =====-->
            <section class="portfolio section" id="portfolio">
                <h2 class="section-title">GALLERY</h2>

                <div class="portfolio__container bd-grid">

                    {% for portfolio in portfolios %}
                    <div class="portfolio__img">
                        <img src="{{ portfolio.image.url }}" alt="">

                        <div class="portfolio__link">
                            <a href="{{ portfolio.image.url }}" data-lightbox="{{ portfolio.image.url }}" data-title="{{ portfolio.long_description }}" class="portfolio__link-name">{{ portfolio.short_description }}</a>
                        </div>
                    </div>
                    {% endfor %}

                </div>
            </section>

        </main>

        <!--===== FOOTER =====-->
        <footer class="footer section">
            <div class="footer__container bd-grid">
                <div class="footer__data">
                    <h2 class="footer__title">{{ home.name }}</h2>
                    <p class="footer__text">Hope u liked it <3</p>
                </div>

                <div class="footer__data">
                    <h2 class="footer__title">EXPLORE</h2>
                    <ul>
                        <li><a href="#home" class="footer__link">Home</a></li>
                        <li><a href="#about" class="footer__link">About</a></li>
                        <li><a href="#skills" class="footer__link">Games</a></li>
                        <li><a href="#portfolio" class="footer__link">Gallery</a></li>
                    </ul>
                </div>
                
                <div class="footer__data">
                    <h2 class="footer__title">FOLLOW</h2>
                    <a href="https://thehealerone.tumblr.com/" class="footer__social"><i class='bx bxl-tumblr' ></i></a>
                </div>


            </div>
        </footer>

        <!--===== SCROLL REVEAL =====-->
        <script src="https://unpkg.com/scrollreveal"></script>

        <!--===== MAIN JS =====-->
        <script src="{% static 'assets/js/main.js' %}"></script>

        <!--===== GALLERY JS =====-->
        <script src="{% static 'assets/js/lightbox-plus-jquery.min.js' %}"></script>
        <!--===== LIGHT / DARK THEME =====-->
        <script type="text/javascript">

		    var setTheme = localStorage.getItem('theme')
		    console.log('theme:', setTheme)

		    if (setTheme == null){
			    swapStyle('{% static 'assets/css/styles.css' %}')
		    }else{
			    swapStyle(setTheme)
		    }

		    function swapStyle(sheet){
			    document.getElementById('stylesheet1').href = sheet
			    localStorage.setItem('theme', sheet)
		    }

		</script>

    </body>
</html>